services:
  redis:
    image: redis:latest
  api:
    build: .
    environment:
      REDIS_HOST: redis
    ports:
      - "9090:9090"
    volumes:
      - .:/usr/src/app
    command: falcon serve --bind http://0.0.0.0:9090
    
  